### ISSUE TITLE
Normalize hex encodings

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#33]
Really often, too many characters are encoded hex.  For instance, you often see `http://example.com/%7Euser` which is a needless incoding for `http://example.com/~user`.  The `Fast.xs` marks this as TODO.

The correcting of this superfluous encoding is a bit difficult: you probably need to keep multi-byte encodings of UTF8 characters in HEX form.

**Comment by sysread** [comment]
Yeah, I left this one as a `TODO` because I'm still not sure how to even detect whether an unnecessarily encoded reserved char is truly that char or if it is just the first byte in a multi-byte glyph.

I could do it by decoding the entire string and then re-encoding it completely, but that's likely to be expensive. I suppose we could go with that implementation and replace it if we come up with something more efficient.

**Comment by sysread** [comment]
This should also cover converting `+` to `%20` (https://github.com/sysread/URI-Fast/issues/31).

**Comment by markov2** [comment]
The detection is not too hard: when the byte is ascii (first digit <8), it should be decoded.  For UTF8, the first bits in the first tell you how many bytes to skip.  But it is easier to test for the continuation bits: all follow-up bytes start with '10'.  So actually very simple: bluntly decode all printable chars below `%80`

**Comment by sysread** [comment]
If I do it by re-encoding each string, I can also do that and case normalization in a single pass.

**Comment by sysread** [comment]
I've implemented this way in 5a1343a. If you have the time (and need) to implement something more efficient that can do the decoding and re-encoding in a single pass, I would very much appreciate the contribution.
